### ISSUE TITLE
Does not appear in dashboard

### ISSUE THREAD

**Issue by Mark-Kiwi** [fellinga/node-red-contrib-ui-time-scheduler#13]
When I add this or use the example, there is no schedule or + button to access in the dashboard.
In the example I only see the switch.
I've tried unloading and reloading but get the same result
![Schedule problem](https://user-images.githubusercontent.com/52309187/100557436-13391980-330e-11eb-9b26-afa9bdef50ad.JPG)

**Comment by fellinga** [comment]
Any warnings at the node-red flow editor? It seems as if the node "node-red-contrib-ui-time-scheduler" is not installed.

Can you see the node at the flow-editor?
![flow-editor](https://user-images.githubusercontent.com/26927863/100558490-fc170f00-32ae-11eb-9910-f89784fc2e8c.png)

**Comment by fellinga** [comment]
Seems to be solved..
Feel free to re-open this if your problem still exists.
