### ISSUE TITLE
Add option to display monday as first day of week and add localizations

### ISSUE THREAD

**Issue by sonntam** [fellinga/node-red-contrib-ui-time-scheduler#15]
Thank you for the very useful node-red extension. I'm already using it to time my christmas lighting.

I'd like to see a checkbox setting that changes the first displayed weekday to monday in the UI. Otherwise it  looks very unusual to me 😉

Also, a possibility to localize the short day strings (e.g. German "So", "Mo", "Di", "Mi", "Do", "Fr", "Sa") would be excellent.

**Comment by fellinga** [comment]
I am glad you like it!

v0.4.6 is now available, adds translation to weekdays and you can now change the first day of the week. Please let me know what you think!

**Comment by sonntam** [comment]
It's working great - thanks!
