### ISSUE TITLE
It works but not for long time

### ISSUE THREAD

**Issue by jean-luc1203** [fellinga/node-red-contrib-ui-time-scheduler#16]
Hi, I've been looking for a node that can graphically manage the time schedule of my blinds for a while. And now I found yours !!!!
Unfortunately, it works for a few minutes and then the outputs set themselves to the boolean value "false". 
The schedule file is well informed. It's well loaded but it's as if it's no longer taken into account by the node. 
An NR start/stop doesn't change anything. 
I have to erase the programming of a blind with the delete key and reprogram it to work again. But again not long.

_P.S (I'm running this NR node in a VM) and not in production on my Pi._

**Thanks for the help**.

screenshots:
My flow:
![image](https://user-images.githubusercontent.com/44665500/102103830-c422d680-3e2d-11eb-8ae9-8675dfac01ad.png)

![image](https://user-images.githubusercontent.com/44665500/102103459-4f4f9c80-3e2d-11eb-9a32-55ec9ba2ac13.png)
Add blind #2 
![image](https://user-images.githubusercontent.com/44665500/102103531-68f0e400-3e2d-11eb-9fc2-765c2dca783d.png)
Thats ok
![image](https://user-images.githubusercontent.com/44665500/102103576-74dca600-3e2d-11eb-92bc-a50b2c677ffa.png)
The debug window shows that it works and all of a sudden the North blind displays false ?
![image](https://user-images.githubusercontent.com/44665500/102104170-267bd700-3e2e-11eb-9830-35122ab91300.png)

![image](https://user-images.githubusercontent.com/44665500/102103673-92aa0b00-3e2d-11eb-9c24-ae2a368c3548.png)
Dashboard
![image](https://user-images.githubusercontent.com/44665500/102103716-9ccc0980-3e2d-11eb-949a-f2241ad42bc9.png)
The data into the file
![image](https://user-images.githubusercontent.com/44665500/102104554-9b4f1100-3e2e-11eb-82a6-9341400ff083.png)

**Comment by fellinga** [comment]
Definitely odd. Your flow is kind of complicated (many devices) can you reproduce this issue with fewer devices as well?
In order to see why this is happening, I would need you to export the flow and post it here. It would also help if you could attach the timers file to your reply.

Thanks

**Comment by jean-luc1203** [comment]
Thank you for your quick reaction, so I'm the one who's caught up in the rush ;-)

Concerning the schedules you are perfectly right, I hadn't checked what I was taking as a schedule, there I took days on the weekends. Sorry, I didn't pay enough attention to my tests.
But the problem remains the same
As soon as I have a bit of time, in a few minutes, I take off some devices to see if it gets better.

Yes i'm using the last one
![image](https://user-images.githubusercontent.com/44665500/102112003-65625a80-3e37-11eb-85a5-6b4d143820e5.png)

Here is just at the startup of NR:
![image](https://user-images.githubusercontent.com/44665500/102111777-1caaa180-3e37-11eb-9d18-33ab7b006262.png)

Here is my flow:
`[{"id":"d6733eb1.f0ffd","type":"tab","label":"Flow 6","disabled":false,"info":""},{"id":"8f8cecd1.4ec9f","type":"comment","z":"d6733eb1.f0ffd","name":"### This scenario is permanent and requires a file to read an write to ###","info":"","x":280,"y":60,"wires":[]},{"id":"16b45e9f.808be1","type":"file","z":"d6733eb1.f0ffd","name":"WriteFile","filename":"/home/pi/Documents/time-schedule0.txt","appendNewline":true,"createDir":true,"overwriteFile":"true","encoding":"none","x":520,"y":160,"wires":[[]]},{"id":"9c3f8b62.d8d588","type":"inject","z":"d6733eb1.f0ffd","name":"FireAfterReboot","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":"0.5","topic":"","payload":"","payloadType":"date","x":120,"y":120,"wires":[["c419ac33.98799"]]},{"id":"c419ac33.98799","type":"file in","z":"d6733eb1.f0ffd","name":"ReadFile","filename":"/home/pi/Documents/time-schedule0.txt","format":"utf8","chunk":false,"sendError":false,"encoding":"none","x":300,"y":120,"wires":[["e7b76de3.79a07","838558b2.511968"]]},{"id":"d21e6114.9eb66","type":"ui_switch","z":"d6733eb1.f0ffd","name":"","label":"Store #1","tooltip":"","group":"b70560dc.4da58","order":1,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":520,"y":200,"wires":[[]]},{"id":"e7b76de3.79a07","type":"ui_time_scheduler","z":"d6733eb1.f0ffd","group":"533abd6f.c30b24","name":"","startDay":"0","refresh":"10","devices":["Store #1","Store #2","Store #3","Store #4","Store #5","Store #6","Store #7","Store Nord","Store Jura","Store Sud"],"customPayload":false,"eventMode":false,"outputs":11,"order":1,"width":6,"height":1,"x":290,"y":280,"wires":[["16b45e9f.808be1","838558b2.511968"],["d21e6114.9eb66","b07f38e5.afbc88"],["8d99f568.def808","8f890883.01eab8"],["96d8ef1e.95583"],["e236d82e.a65fb8"],["1f040ccc.d93fb3"],["f08c0311.5e472"],["129040ca.df76cf"],["ec8d1260.8e31f","7c5d895c.b50588"],["569aa56b.6ea56c"],["edb735b7.704c28"]]},{"id":"8d99f568.def808","type":"ui_switch","z":"d6733eb1.f0ffd","name":"","label":"Store #2","tooltip":"","group":"b70560dc.4da58","order":2,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":520,"y":240,"wires":[[]]},{"id":"96d8ef1e.95583","type":"ui_switch","z":"d6733eb1.f0ffd","name":"","label":"Store #3","tooltip":"","group":"b70560dc.4da58","order":3,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":520,"y":280,"wires":[[]]},{"id":"e236d82e.a65fb8","type":"ui_switch","z":"d6733eb1.f0ffd","name":"","label":"Store #4","tooltip":"","group":"b70560dc.4da58","order":4,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":520,"y":320,"wires":[[]]},{"id":"1f040ccc.d93fb3","type":"ui_switch","z":"d6733eb1.f0ffd","name":"","label":"Store #5","tooltip":"","group":"b70560dc.4da58","order":5,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":520,"y":360,"wires":[[]]},{"id":"f08c0311.5e472","type":"ui_switch","z":"d6733eb1.f0ffd","name":"","label":"Store #6","tooltip":"","group":"b70560dc.4da58","order":6,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":520,"y":400,"wires":[[]]},{"id":"129040ca.df76cf","type":"ui_switch","z":"d6733eb1.f0ffd","name":"","label":"Store #7","tooltip":"","group":"b70560dc.4da58","order":7,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":519.6666870117188,"y":437,"wires":[[]]},{"id":"ec8d1260.8e31f","type":"ui_switch","z":"d6733eb1.f0ffd","name":"","label":"Store Nord","tooltip":"","group":"df8c99f5.079e88","order":1,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":530,"y":480,"wires":[[]]},{"id":"569aa56b.6ea56c","type":"ui_switch","z":"d6733eb1.f0ffd","name":"","label":"Store Jura","tooltip":"","group":"df8c99f5.079e88","order":2,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":530,"y":520,"wires":[[]]},{"id":"edb735b7.704c28","type":"ui_switch","z":"d6733eb1.f0ffd","name":"","label":"Store Sud","tooltip":"","group":"df8c99f5.079e88","order":3,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":520,"y":560,"wires":[[]]},{"id":"838558b2.511968","type":"debug","z":"d6733eb1.f0ffd","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":530,"y":120,"wires":[]},{"id":"b07f38e5.afbc88","type":"debug","z":"d6733eb1.f0ffd","name":"store 1","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":670,"y":200,"wires":[]},{"id":"8f890883.01eab8","type":"debug","z":"d6733eb1.f0ffd","name":"store 2","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":670,"y":240,"wires":[]},{"id":"7c5d895c.b50588","type":"debug","z":"d6733eb1.f0ffd","name":"store nord","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":700,"y":480,"wires":[]},{"id":"b70560dc.4da58","type":"ui_group","name":"Stores","tab":"2936b813.6cde68","order":2,"disp":true,"width":"3","collapse":false},{"id":"533abd6f.c30b24","type":"ui_group","name":"Sélection Jours - heures","tab":"2936b813.6cde68","order":1,"disp":true,"width":"6","collapse":false},{"id":"df8c99f5.079e88","type":"ui_group","name":"Stores Extension","tab":"2936b813.6cde68","order":3,"disp":true,"width":3,"collapse":false},{"id":"2936b813.6cde68","type":"ui_tab","name":"Scheduler Demo","icon":"dashboard","order":1,"disabled":false,"hidden":false}]`

**Comment by jean-luc1203** [comment]
here is what's in the file:

pi@lubuntu:~/Documents$ cat time-schedule0.txt

**{"timers":[{"starttime":1607932800000,"days":[1,0,0,0,0,0,0],"output":"1","endtime":1607965200000},{"starttime":1607968800000,"days":[0,0,0,0,0,1,0],"output":"7","endtime":1607972400000}]}**

**Comment by jean-luc1203** [comment]
I have deleted several devices and there are 4 left. I must be doing something wrong but I don't see what it is. 

![image](https://user-images.githubusercontent.com/44665500/102114904-0ef71b00-3e3b-11eb-9a8d-761c53eb0f94.png)

I've removed all schedule and try with store 1. No way

![image](https://user-images.githubusercontent.com/44665500/102115116-6301ff80-3e3b-11eb-9e36-d0f44811ce18.png)

**Comment by fellinga** [comment]
The attached schedule from the most recent post had one timer that should run every Saturday from 18:36 until 18:41.
It is supposed to turn ON at 18:36 an turn OFF at 18:41 (not at 42, it actually turns the device off at 41). The timer from the screenshot above where the flow editor is visible has a timer that runs only on Sundays.

I don't think that you are currently test anything with Saturday or Sunday, do you? Can you describe an example where you add a timer, tell me what you would expect to happen and then what actually happens (and when).

**Comment by jean-luc1203** [comment]
[time-schedule0.txt](https://github.com/fellinga/node-red-contrib-ui-time-scheduler/files/5707853/time-schedule0.txt)
Sorry for my late answer, my internet line was ripped out by an excavator.
I do with my phone and it's not easy ;-)

[time-schedule0.txt](https://github.com/fellinga/node-red-contrib-ui-time-scheduler/files/5707867/time-schedule0.txt)

Here we go. Started with no schedule:
![image](https://user-images.githubusercontent.com/44665500/102460164-e17ebd00-4046-11eb-99f5-c1c533738b09.png)
I set a timer on blind No 2 at 08h52, end at 08h57 for Sunday, the Bolean value remains false. It should change to true ? just ?
![image](https://user-images.githubusercontent.com/44665500/102460529-6a95f400-4047-11eb-9cfc-05aaef258023.png)
![image](https://user-images.githubusercontent.com/44665500/102460541-6f5aa800-4047-11eb-881c-409212b9fdb5.png)
I made another timer on blind 4, still nothing happens on the boolean side.  It should change to true, right ?
![image](https://user-images.githubusercontent.com/44665500/102460708-af218f80-4047-11eb-8833-2913cde93e07.png)
![image](https://user-images.githubusercontent.com/44665500/102460720-b3e64380-4047-11eb-856c-6a8b471fdfba.png)

Here is the flow i'm using:
`[{"id":"d6733eb1.f0ffd","type":"tab","label":"Flow 6","disabled":false,"info":""},{"id":"8f8cecd1.4ec9f","type":"comment","z":"d6733eb1.f0ffd","name":"### This scenario is permanent and requires a file to read an write to ###","info":"","x":280,"y":60,"wires":[]},{"id":"16b45e9f.808be1","type":"file","z":"d6733eb1.f0ffd","name":"WriteFile","filename":"/home/pi/Documents/time-schedule0.txt","appendNewline":true,"createDir":true,"overwriteFile":"true","encoding":"none","x":520,"y":160,"wires":[[]]},{"id":"9c3f8b62.d8d588","type":"inject","z":"d6733eb1.f0ffd","name":"FireAfterReboot","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":"0.5","topic":"","payload":"","payloadType":"date","x":120,"y":120,"wires":[["c419ac33.98799"]]},{"id":"c419ac33.98799","type":"file in","z":"d6733eb1.f0ffd","name":"ReadFile","filename":"/home/pi/Documents/time-schedule0.txt","format":"utf8","chunk":false,"sendError":false,"encoding":"none","x":300,"y":120,"wires":[["e7b76de3.79a07","838558b2.511968"]]},{"id":"d21e6114.9eb66","type":"ui_switch","z":"d6733eb1.f0ffd","name":"","label":"Store #1","tooltip":"","group":"b70560dc.4da58","order":1,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":520,"y":200,"wires":[[]]},{"id":"e7b76de3.79a07","type":"ui_time_scheduler","z":"d6733eb1.f0ffd","group":"533abd6f.c30b24","name":"","startDay":"0","refresh":"25","devices":["Store #1","Store #2","Store #3","Store #4"],"customPayload":false,"eventMode":false,"outputs":5,"order":1,"width":6,"height":1,"x":290,"y":280,"wires":[["16b45e9f.808be1","838558b2.511968"],["d21e6114.9eb66","b07f38e5.afbc88"],["8d99f568.def808","8f890883.01eab8"],["96d8ef1e.95583"],["e236d82e.a65fb8"]]},{"id":"8d99f568.def808","type":"ui_switch","z":"d6733eb1.f0ffd","name":"","label":"Store #2","tooltip":"","group":"b70560dc.4da58","order":2,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":520,"y":300,"wires":[[]]},{"id":"96d8ef1e.95583","type":"ui_switch","z":"d6733eb1.f0ffd","name":"","label":"Store #3","tooltip":"","group":"b70560dc.4da58","order":3,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":520,"y":400,"wires":[[]]},{"id":"e236d82e.a65fb8","type":"ui_switch","z":"d6733eb1.f0ffd","name":"","label":"Store #4","tooltip":"","group":"b70560dc.4da58","order":4,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":520,"y":460,"wires":[[]]},{"id":"838558b2.511968","type":"debug","z":"d6733eb1.f0ffd","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":530,"y":120,"wires":[]},{"id":"b07f38e5.afbc88","type":"debug","z":"d6733eb1.f0ffd","name":"output 1","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":520,"y":240,"wires":[]},{"id":"8f890883.01eab8","type":"debug","z":"d6733eb1.f0ffd","name":"output 2","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":520,"y":340,"wires":[]},{"id":"b70560dc.4da58","type":"ui_group","name":"Stores","tab":"2936b813.6cde68","order":2,"disp":true,"width":"3","collapse":false},{"id":"533abd6f.c30b24","type":"ui_group","name":"Sélection Jours - heures","tab":"2936b813.6cde68","order":1,"disp":true,"width":"6","collapse":false},{"id":"2936b813.6cde68","type":"ui_tab","name":"Scheduler Demo","icon":"dashboard","order":1,"disabled":false,"hidden":false}]`

**Comment by fellinga** [comment]
The screenshots and the files show that you have created timers that would run on Saturdays and the other one on Mondays. The consoles date that outputs "false" the whole time says 17/12/2020 which is a Thursday (today). So this is correct.

Try creating a timer that runs on Thursdays and you will see the output to change to "true" if the current time is within the timers range.

**Comment by jean-luc1203** [comment]
I'm sorry, I didn't understand the logic. 
So we get "true" when the programmed time slot has arrived (logic !)
I thought that "true" meant that a timer had been set for the device in question, for example store#2. 
**Now it's clear!**

Would it be possible to have a visual overview of the different timers that have been activated ? (which I thought I would do). 
We can then go and see the details by clicking on the device and look at its settings.
 
In any case, thank you very much **for your patience** and for your answers.

**Comment by fellinga** [comment]
Yes the timer always outputs "false" if no timer is in a defined time range, and also if no timer is defined at all. The only time it changes to "true" is when the current time is between start and end time of one of the created timers.

By "visual overview", do you mean something like this:
![102460529-6a95f400-4047-11eb-9cfc-05aaef258023](https://user-images.githubusercontent.com/26927863/102528072-53cebc00-409e-11eb-903f-423b83fdcbb5.png)

I have been thinking about it in the past, the picture above is just a draft at the moment. But I am open to suggestions, would this be helpful to you?

**Comment by jean-luc1203** [comment]
Yes you got it all figured out, this is exactly what I want to use for my 10 blinds. 
At a glance I can see which ones are programmed, and in addition with your overview I can quickly look at the schedules. It's absolutely TOP !

**Comment by fellinga** [comment]
Okay I'll add this to my todo list. It will be a feature in one of the next updates.
Thanks for bringing this up. 👍

**Comment by jean-luc1203** [comment]
Great. It's really great that we can use your skills with Node Red like this. 
This magical tool that allowed me to set foot in home automation. 
More than the feet, the whole body ;-)
Again it's 😎 Thank’s a lot.

**Comment by fellinga** [comment]
I am glad it helps!

Make sure to check out the event mode as well, might be even the better solution for blinds. The difference to the default mode is that you can program single events - the node doesn't output anything except if the defined time matches with the current time. That way you can: send "true" at lets say 10:00 and "false" at 13:00 while nothing is sent in between, before or after. And with custom payloads you can control almost any device.

![11](https://user-images.githubusercontent.com/26927863/102538544-b29b3200-40ac-11eb-8987-d90410108fd9.png)

**Comment by jean-luc1203** [comment]
Good idea, so I tried it and here are the results
_The choices:_
![image](https://user-images.githubusercontent.com/44665500/102599499-d8acea80-411d-11eb-8a5b-ea2243c44e32.png)
_My setup :_
![image](https://user-images.githubusercontent.com/44665500/102599532-e498ac80-411d-11eb-88dd-bf7fc6c46231.png)

Result, I receive the booleans several times? and finally it stops. 
What would be perfect would indeed be 1x true and 1x false
The refresh time is fixed at 10 seconds.
Did I do something wrong again? :

18/12/2020 à 10:28:38 node: bbf2a03c.9f1fc
msg.payload : string[168]

"{"timers":[{"starttime":1608283740000,"days":[0,0,0,0,0,1,0],"output":"1","event":true},
{"starttime":1608283800000,"days":[0,0,0,0,0,1,0],"output":"1","event":false}]}↵"

18/12/2020 à 10:28:59 node: output 2
msg.payload : boolean
true
18/12/2020 à 10:29:10 node: output 2
msg.payload : boolean
true
18/12/2020 à 10:29:20 node: output 2
msg.payload : boolean
true
18/12/2020 à 10:29:30 node: output 2
msg.payload : boolean
true
18/12/2020 à 10:29:40 node: output 2
msg.payload : boolean
true
18/12/2020 à 10:29:50 node: output 2
msg.payload : boolean
true
18/12/2020 à 10:30:00 node: output 2
msg.payload : boolean
false
18/12/2020 à 10:30:10 node: output 2
msg.payload : boolean
false
18/12/2020 à 10:30:20 node: output 2
msg.payload : boolean
false
18/12/2020 à 10:30:30 node: output 2
msg.payload : boolean
false
18/12/2020 à 10:30:40 node: output 2
msg.payload : boolean
false
18/12/2020 à 10:30:50 node: output 2
msg.payload : boolean
false

`[{"id":"cb3beebb.25807","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"e4adb792.b4b928","type":"comment","z":"cb3beebb.25807","name":"### This scenario is permanent and requires a file to read an write to ###","info":"","x":260,"y":40,"wires":[]},{"id":"d70763f1.4b52f","type":"file","z":"cb3beebb.25807","name":"WriteFile","filename":"/home/pi/Documents/time-events.txt","appendNewline":true,"createDir":true,"overwriteFile":"true","encoding":"none","x":480,"y":160,"wires":[["82427cdb.b45ad"]]},{"id":"819d5f64.ed886","type":"inject","z":"cb3beebb.25807","name":"FireAfterReboot","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":"0.5","topic":"","payload":"","payloadType":"date","x":100,"y":100,"wires":[["beecfdd1.2ee75"]]},{"id":"beecfdd1.2ee75","type":"file in","z":"cb3beebb.25807","name":"ReadFile","filename":"/home/pi/Documents/time-events.txt","format":"utf8","chunk":false,"sendError":false,"encoding":"none","x":280,"y":100,"wires":[["e329406b.175f","bbf2a03c.9f1fc"]]},{"id":"68b892b0.29a67c","type":"ui_switch","z":"cb3beebb.25807","name":"","label":"Store #1","tooltip":"","group":"b70560dc.4da58","order":2,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":480,"y":200,"wires":[[]]},{"id":"e329406b.175f","type":"ui_time_scheduler","z":"cb3beebb.25807","group":"533abd6f.c30b24","name":"","startDay":"0","refresh":"10","devices":["Store #1 Up / Down","Store #2 Up / Down","Store #3 Up / Down","Store #4 Up / Down","Store #5 Up / Down","Store #6 Up / Down","Store #7 Up / Down","Store #8 Up / Down"],"customPayload":false,"eventMode":true,"outputs":9,"order":2,"width":6,"height":2,"x":270,"y":260,"wires":[["d70763f1.4b52f"],["68b892b0.29a67c","bda097a9.f93e98"],["d454cf05.c25f","187fec50.21b1d4"],["4e0f5d1.9aab5a4"],["eb39b077.308c4"],[],[],[],[]]},{"id":"d454cf05.c25f","type":"ui_switch","z":"cb3beebb.25807","name":"","label":"Store #2","tooltip":"","group":"b70560dc.4da58","order":4,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":480,"y":300,"wires":[[]]},{"id":"4e0f5d1.9aab5a4","type":"ui_switch","z":"cb3beebb.25807","name":"","label":"Store #3","tooltip":"","group":"b70560dc.4da58","order":6,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":480,"y":400,"wires":[[]]},{"id":"eb39b077.308c4","type":"ui_switch","z":"cb3beebb.25807","name":"","label":"Store #4","tooltip":"","group":"b70560dc.4da58","order":8,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":480,"y":460,"wires":[[]]},{"id":"82427cdb.b45ad","type":"debug","z":"cb3beebb.25807","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":630,"y":160,"wires":[]},{"id":"bda097a9.f93e98","type":"debug","z":"cb3beebb.25807","name":"output 1","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":480,"y":240,"wires":[]},{"id":"187fec50.21b1d4","type":"debug","z":"cb3beebb.25807","name":"output 2","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":480,"y":340,"wires":[]},{"id":"bbf2a03c.9f1fc","type":"debug","z":"cb3beebb.25807","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":630,"y":100,"wires":[]},{"id":"b70560dc.4da58","type":"ui_group","name":"Stores","tab":"2936b813.6cde68","order":2,"disp":true,"width":"3","collapse":false},{"id":"533abd6f.c30b24","type":"ui_group","name":"Sélection Jours - heures","tab":"2936b813.6cde68","order":1,"disp":true,"width":"6","collapse":false},{"id":"2936b813.6cde68","type":"ui_tab","name":"Scheduler Demo","icon":"dashboard","order":1,"disabled":false,"hidden":false}]`

**Comment by fellinga** [comment]
This happens because you changed the refresh time to 10 seconds. A refresh time of 10 means, the device checks 6 time per minute if the current time is valid -> therefore you get true/false 6 times. I might remove the refresh property in the future I don't think it is really necessary anymore and 60 should work for everyone.

Just leave it at 60 and you will receive true/false only once per minute.

Btw: I stated working on the overview tab this morning, should be able to deliver soon!

**Comment by jean-luc1203** [comment]
Yes, I understood the 6x10 seconds. Would it make more sense to send the True message once rather than once a minute. To open or close my blind with RFlink I only need to send it once. However, I can ignore the True messages that come afterwards until I get a False that will close the blind.
I am looking forward to the ongoing development!

**Comment by fellinga** [comment]
> Would it make more sense to send the True message once rather than once a minute.

The event mode does exactly that (at a refresh rate of 60 seconds). If you configure an ON Event at 12:00 you will get exactly one TRUE at 12:00:00 and nothing else.

**Comment by jean-luc1203** [comment]
I tested it and **it's perfect for me**! 
I could already start modifying my flows to program my blinds in a visual and pleasant way for my wife and me.
And then update the node with future enhancements. Can I buy you a coffee?

![image](https://user-images.githubusercontent.com/44665500/102620404-40732d80-413e-11eb-87d9-1d6a9d6ce677.png)
![image](https://user-images.githubusercontent.com/44665500/102620443-4c5eef80-413e-11eb-90b7-c7cdfe3faf5e.png)

**Comment by fellinga** [comment]
Thanks for the feedback! I really appreciate it!
I love coffee 💯 but you really don't need to, hearing that it helps you and your wife is value enough!

0.4.7 should be available within the next 30 minutes, it contains the requested addition.. I hope you like it!

**Comment by jean-luc1203** [comment]
Great Job, this is what it can look like. 

![image](https://user-images.githubusercontent.com/44665500/102687708-34947380-41f1-11eb-8356-2376439ffcd9.png)

**Comment by jean-luc1203** [comment]
So if I can, a little look back at the ergonomics of the display.
In use, I see 2 possible improvements.

1)  Being able to select directly in 1 click Monday-Tuesday-Thursday-Wednesday-Friday instead of 1 click per day.
And another selection in 1 click for Saturday-Sunday.

2) To have the possibility to use all or part of the screen to display the overview of the schedules instead of an elevator when there is a lot of devices, as it is my case. It will be more pleasant to read at a glance.

Otherwise, it's a pleasure to use this new screen to plan my blinds :-)

**Comment by fellinga** [comment]
1. I understand that a weekdays / weekends button can be useful but I am not sure if I want to make the list even longer. 

- MO
- TU
- WE
- TH
- FR
- SA
- SU
- WEEKDAYS
- WEEKENDS

I am going to test it live but I looks quite long already.

2. I am not sure what you mean by the elevator. If you refer to the scrollbar, the scrollbar is automatically shown if the list needs more height than the height that you configured in the flow editor.. You would have to adjust the nodes height to something that fits your need, like this:
![nodeHeight](https://user-images.githubusercontent.com/26927863/102833864-a12a9080-43f2-11eb-8c4b-514059610163.png)
I was thinking about completely removing empty devices from the overview, this would shrink the list quite a bit in your case. 
Please let me know what you think!

**Comment by jean-luc1203** [comment]
Concerning the width of the overview display, 
I think that a 2nd column should be provided when the display is too long.
Otherwise it gives something like this that continues downwards, so you have to scroll the screen downwards. Which is not practical. (see below)
Otherwise, yes removing the blinds that are not programmed is a simple but brilliant idea. This is only my point of view in my case. Maybe not in another case
For weekdays, or weekends, it's great for me. I don't find it too long, but fast to select.
Thank you for the follow-up in any case
![image](https://user-images.githubusercontent.com/44665500/102867512-2d5fa680-4439-11eb-9a87-c0af2be540ea.png)

![image](https://user-images.githubusercontent.com/44665500/102867172-a7436000-4438-11eb-8aba-6aa9b3fdeb12.png)

**Comment by fellinga** [comment]
Thanks for the suggestions, a second column seems to be a good option (if width >= 12 or so). 
I'll add it to my todo list and will let you know as soon as it's available (might take a little longer though, since I am working on some new features/nodes).

**Comment by fellinga** [comment]
> 1. Being able to select directly in 1 click Monday-Tuesday-Thursday-Wednesday-Friday instead of 1 click per day.
>    And another selection in 1 click for Saturday-Sunday.

wanted to mention #36 here. it is not a 1 click for weekdays and weekend but it should simplify things.
