### ISSUE TITLE
How can I change the language?

### ISSUE THREAD

**Issue by cvarino** [fellinga/node-red-contrib-ui-time-scheduler#19]
Nice node!
 I saw that there are two languages: “de” and “en-US” But how can I change between them?
I can also send u Spanish translation.

**Comment by fellinga** [comment]
**Flow editor (backend):**
The language for the node-red-flow-editor can be changed within the settings (they don't have Spanish though) :
![node-red-flow-language](https://user-images.githubusercontent.com/26927863/102886007-96a0e300-4454-11eb-9cca-9edd30e073fc.png)
This changes the time-scheduler nodes language at the backend (flow-editor).

**Dashboard (frontend):**
The language for the frontend seems to match the servers operation system settings. I am running an English development server which displays the time-scheduler node in English (at the dashboard), while a German Raspbian OS displays the time-scheduler in German (at the dashboard). So my guess is that if you would add a Spanish translation file to the node and change the servers language the Spanish it would display the node in Spanish.

**Comment by cvarino** [comment]
It's a shame,
I have looked at the dashboard version on my beagleboneblack and it is 2.9.8 it is the most updated since I am running node.js v6.0 and I have too many things running in this board. So I don't dare to upgrade it to v8.0.

Anyway, Iprepared the ES files if you want you can create a folder named ES and I will upload the files.

**Comment by fellinga** [comment]
That's so close.. but yes all the community made dashboard widgets require 2.10.0.

You can upload the file here in your comment! I'd appreciate it!

**Comment by cvarino** [comment]
[es.zip](https://github.com/fellinga/node-red-contrib-ui-time-scheduler/files/5736006/es.zip)

**Comment by fellinga** [comment]
Many thanks!

**Comment by cvarino** [comment]
Finally I adapted your design to a dashboard template. So it is working now. I prefer to edit in the same rows and only one device.
Thanks a lot!

PD: I send you the dashboard template if you want to use anything

<script>
this.scope.days = ["LU","MA","MI","JU","VI","SA","DO"];

</script>
<style>
    .inline input{
  float:left;
}
    .weekDay {
				width: 100%;
				max-width: 40px;
				display:inline-block;
				line-height: 40px;
				border-radius: 50%;
				color: var(--nr-dashboard-widgetTextColor);
				background-color: var(--nr-dashboard-pageTitlebarBackgroundColor);
				opacity: 0.4;
			}
	.weekDayActive {
	    width: 100%;
				max-width: 40px;
				display:inline-block;
				line-height: 40px;
				border-radius: 50%;
				color: var(--nr-dashboard-widgetTextColor);
				background-color: var(--nr-dashboard-pageTitlebarBackgroundColor);
				opacity: 1;
			}
</style>
<table style="width: 100%; border-spacing: 0px;">
	                <tr ng-repeat-start="(key,timer) in msg.payload" style="background-color:var(--nr-dashboard-pageTitlebarBackgroundColor)">
                       <th> #</th>
                       <th colspan="3"> Inicio </th>
                       <th colspan="3"> Acción </th>
	                </tr>
	                <tr >
						<td align=center> <div  ng-click="msg.payload.splice(key,1);send(msg)"> <md-icon class = "material-icons">delete_outline</md-icon> </div> </td>
						<td colspan="3"  align=center>
						    <table><tr><td>
						     <input style="width: 40px;" type="number" name="HourInput" ng-model="timer.HH" min="0" max="23" maxlength="2" size="2" ng-change="send(msg)" /> 
							 </td><td>:</td><td><input style="width: 40px;" type="number" name="MinutesInput" ng-model="timer.mm" min="0" max="59"  size="2" ng-change="send(msg)" /> 
						    </tr></table></td>
						<td colspan="3" align=center >  <input type="number" name="EventInput" ng-model="timer.event" min="0" max="40" ng-change="send(msg)" /> </td>
				    </tr>
					<tr>
						<td ng-repeat="day in days"  style="width:14%;margin: 0 2%;"> 
							<div  ng-if="!timer.days[$index]" class="weekDay" align=center ng-click="timer.days[$index]=1;send(msg)">
								{{day}}	
							</div>
							<div ng-if="timer.days[$index]" class="weekDayActive" align=center ng-click="timer.days[$index]=0;send(msg)">
								{{day}}	
							</div>
						</td>
					</tr>
					<tr ng-repeat-end style="height: 6px;"> </tr>
</table>
<br>
<div align=right> 
<md-button  class = "md-fab"  ng-click="msg.payload.push({})"> <md-icon class = "material-icons">add</md-icon> </md-button>
</div>

**Comment by fellinga** [comment]
Just wanted to mention [this PR](https://github.com/node-red/node-red/pull/2796) for future reference. It allows to change the language for Node-Red and the Node-Red-Dashboard from the settings file.
