### ISSUE TITLE
[Enhancement] Can time scheduler node support a GUI time picker? 

### ISSUE THREAD

**Issue by chc69** [fellinga/node-red-contrib-ui-time-scheduler#20]
Hi @fellinga 
This is great ui node of scheduler. 
My use case is let user to configure the schedule and event on an iPad, but it is difficult to do it with keyboard on iPad. 
So, 
- Is that possible to make the time setting as a GUI interface on dashboard? 
- Is that possible to let custom event become a dropdown list? i.e. configure eventOption from input then can see the options on GUI dropdown list. 

Both those two requirement are trying to give user a better UX. 
Thank you.

**Comment by fellinga** [comment]
Thanks for your suggestions!

1 - The time setting works pretty well on all kind of browser and devices... they just don't work as well on Safari & Firefox. I started working on this and I think I already found a solution.
2 - It's definitely possible to prefill a dropdown box, but this would have to be a global setting. Would it help if you (as admin) could configure event options at the flow editor, that then show up (for every single timer) at the GUI?

**Comment by chc69** [comment]
Hi @fellinga 
Thanks for reply. 

1. What I expect the GUI interface is like this [GUI time picker](https://user-images.githubusercontent.com/32812848/61620097-6dcd5a80-ac70-11e9-915d-602bb3147010.png)
As I said an input text box is too difficult for user w/ virtual keyboard on iPad. 

2. I would expect each Device should has it's own eventOption. The scenario is I will setup many profile for LED to save energy by your time shceduler. So, I would like to set the profile name as the eventOption for LED devices only since I still have another devices like HVAC, refrigerator which will have their own profiles. 

It works well when I put file name on custom event field. Form the feature perspective, this is great. I just hope to provide a better UX to user with single finger.

**Comment by fellinga** [comment]
I just double checked v0.4.7 with an up2date iPad and it already shows the GUI time picker:
![iPad](https://user-images.githubusercontent.com/26927863/103208300-95fac780-4900-11eb-9522-220306f7341a.png)


Does it look different on your iPad, what version are you using?

**Comment by chc69** [comment]
Sorry, my mistake. I am using Safari on Mac now. The time picker works on Mac Chrome. cheers.

**Comment by fellinga** [comment]
Okay, good to know though! I've just released 0.4.8, it improves the time input handling for Firefox and is ready for the next Safari release (Safari 15 for Mac will support the native time picker).

Going to see what I can do with the custom event options now..

**Comment by fellinga** [comment]
1.8.0 now offers configurable event options! I'd appreciate your feedback!
