### ISSUE TITLE
Ask about a new feature

### ISSUE THREAD

**Issue by schamu** [fellinga/node-red-contrib-ui-time-scheduler#22]
Hi there,
is it possible to install a switch for each device that activates or deactivates it?
If the device is activated, the output is sent regularly.
If the device is deactivated, nothing is sent on the output.

**Comment by fellinga** [comment]
Hi Thomas,

so you want to pause specific devices without deleting all the timers? You can achieve this pretty easily actually by just adding a switch node to the `ui schedulers` output and then check if a certain condition is true. Like so:

`[{"id":"991c539f.fb285","type":"comment","z":"d8cb3879.806298","name":"### This scenario is permanent and requires a file to read an write to ###","info":"","x":320,"y":60,"wires":[]},{"id":"ef11c701.cd9fa8","type":"file","z":"d8cb3879.806298","name":"WriteFile","filename":"/home/debian/Documents/time-schedule0.txt","appendNewline":true,"createDir":true,"overwriteFile":"true","encoding":"none","x":700,"y":60,"wires":[[]]},{"id":"7822012a.876838","type":"inject","z":"d8cb3879.806298","name":"FireAfterReboot","props":[{"p":"payload","v":"","vt":"date"},{"p":"topic","v":"","vt":"string"}],"repeat":"","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":160,"y":120,"wires":[["2920de2a.a86312"]]},{"id":"2920de2a.a86312","type":"file in","z":"d8cb3879.806298","name":"ReadFile","filename":"/home/debian/Documents/time-schedule0.txt","format":"utf8","chunk":false,"sendError":false,"encoding":"none","x":340,"y":120,"wires":[["18d69559.b452cb"]]},{"id":"ee4ea530.9cd2b","type":"ui_switch","z":"d8cb3879.806298","name":"","label":"MyDevice","tooltip":"","group":"bfe48a3e.1b0f4","order":1,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":960,"y":120,"wires":[[]]},{"id":"18d69559.b452cb","type":"ui_time_scheduler","z":"d8cb3879.806298","group":"bfe48a3e.1b0f4","name":"","startDay":"1","refresh":60,"devices":["Device 1"],"customPayload":false,"eventMode":false,"outputs":2,"order":2,"width":"6","height":"1","x":510,"y":120,"wires":[["ef11c701.cd9fa8"],["45569cf5.5b1b84"]]},{"id":"45569cf5.5b1b84","type":"switch","z":"d8cb3879.806298","name":"check global.MyDevice","property":"myDevice","propertyType":"global","rules":[{"t":"true"}],"checkall":"true","repair":false,"outputs":1,"x":740,"y":120,"wires":[["ee4ea530.9cd2b"]]},{"id":"72109111.b16df","type":"ui_switch","z":"d8cb3879.806298","name":"","label":"MyDeviceEnabled","tooltip":"","group":"bfe48a3e.1b0f4","order":3,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":530,"y":180,"wires":[["dde1bb57.77ae58"]]},{"id":"dde1bb57.77ae58","type":"change","z":"d8cb3879.806298","name":"","rules":[{"t":"set","p":"myDevice","pt":"global","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":740,"y":180,"wires":[[]]},{"id":"8f047fb5.394ab","type":"inject","z":"d8cb3879.806298","name":"FireAfterReboot","props":[{"p":"payload"}],"repeat":"","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"true","payloadType":"bool","x":160,"y":180,"wires":[["72109111.b16df"]]},{"id":"bfe48a3e.1b0f4","type":"ui_group","name":"PermDemo","tab":"2936b813.6cde68","order":5,"disp":true,"width":"6","collapse":false},{"id":"2936b813.6cde68","type":"ui_tab","name":"Scheduler Demo","icon":"dashboard","order":1,"disabled":false,"hidden":false}]`

Please let me know if does what you meant.

**Comment by schamu** [comment]
Hi there,
Thank you for your answer.
Yes, that's what I meant.
That's how I've already solved it.
But it would be nice if you could also set it directly in the scheduler.

**Comment by fellinga** [comment]
Okay good, just wanted to give you an immediate solution.

Pausing specific timers is definitely going to be added soon, just haven't thought about pausing the whole device at once! I am going to add a solution for this as well as soon as I manage to implement the specific pausing function. I'll give you an update here as soon as it is finished!

Thanks for your suggestion 👍

**Comment by connermacleod69** [comment]
Hi,
would it be possible to change your fantastic timer so that I could turn lights on at 20:00 and turn them of the day after at 6:00. Or should I do 2 timers 20:00 till 23:59 and 06:00? Or turn them on at 06:00 and off at 20:00 and inverse the output?
Regards,
Serge

**Comment by fellinga** [comment]
Hi @connermacleod69, 

I am currently not planning on changing the 24hour limit. You can simply add two timers, just like you said, from 20:00 to 23:59 and another one from 00:00 to 06:00. Another possibility would be to activate the event mode, and set an ON event at 20:00 and an OFF event at 06:00 in the morning.

**Comment by connermacleod69** [comment]
Hi @fellinga,
sorry I missed the on/off item...This now works for me.
Regards,
Serge

**Comment by fellinga** [comment]
@schamu 1.9.0 now has the ability pause devices directly from the GUI and from incoming messages! I'd appreciate your feedback!
