### ISSUE TITLE
Enhancement save schedule, is lost on each deploy

### ISSUE THREAD

**Issue by SergiuToporjinschi** [fellinga/node-red-contrib-ui-time-scheduler#24]
Hi,
Very nice node 👍 keep it going.

I'm planning to make my node to accept also your schedule format. My node needs an interface for scheduling. Currently, I use a json in admin interface but I would like to have something that you did for a friendly interface and I don't have time to implement that and to be honest, if you are maintaining yours is ok.
My node controls a heater [**heater-controller**](https://github.com/SergiuToporjinschi/node-red-contrib-heater-controller).
And I've installed  **ui-time-scheduler** on my node-red dev instance and I noticed that you don't save the schedules and on every deploy the user has to input again the values
Maybe you are thinking to save that because when you are working with node-red you do a lot of changes and you have to redeploy offen the flows.
Have have fun!
Sergiu

**Comment by fellinga** [comment]
Hi,

it is very easy to save schedules already. You can save and reinject them on every deploy. 

The Readme even shows a screenshot of how it is done:
![time-scheduler-flow](https://user-images.githubusercontent.com/26927863/106369828-e4aedd80-6354-11eb-94fd-09c4592857ea.jpg)

Did you see that?

**Comment by SergiuToporjinschi** [comment]
Yes I saw it :) I know that there are ways to do that I think you can save it in flow or in general but when you have a schema like this .... you want to have less nodes :D 
![image](https://user-images.githubusercontent.com/9376439/106371125-690b5b80-6369-11eb-888f-3e12e47a7791.png)

**Comment by fellinga** [comment]
The node red API does not allow the alter a nodes property from the UI - or at least not in a very good way - because you would have to hit the deploy button from the flow editor after (see [here](https://discourse.nodered.org/t/edit-node-config-from-dashboard/20495)).

**Comment by SergiuToporjinschi** [comment]
I don't understand why, I could do it and works fine.

**Comment by fellinga** [comment]
Your node saves the schedule directly **within the flow editor** - after that you just deploy and it is all good. Unfortunately it is not that easy if you want to change properties from anywhere else. 

Do you have an example of where you changed your properties from outside the (flow editor) node settings?

**Comment by SergiuToporjinschi** [comment]
Yes, I'm saving on node context with node.context().set("config", values);
like the topic setCalendar ? the schedule be set in editor in a text field but also can be send as input message. but I think is not changing the editor content ... or that's your problem? 
Nevertheless the implementation of an ui node is a nightmare, I have to do so many hacks to have a clean flow.... I'm currently doing a heavy refactoring on it because after a year or so is hard to read the code and now I know better what I want

**Comment by SergiuToporjinschi** [comment]
Like for example to change refresh value which appear in flow editor but to do it from interface or? what do you  mean by Properties?

**Comment by fellinga** [comment]
Yes with properties I meant values like the refresh property but I see now that you were talking about the nodes context. By default, whenever something is stored into a nodes context then it is gone after a redeploy as well. I suppose you are using ["localfilesystem" for your "contextStorage"](https://nodered.org/docs/user-guide/context#saving-context-data-to-the-file-system)?

**Comment by SergiuToporjinschi** [comment]
yes I'm using LocalFileSystem.
If you want to messages from front to change the properties, maybe a config/server node can solve your problem. I did not test that but are some how different;
you can take a look on mqtt node, there is a server node. I don't know too much about that but I think it worth's to take a look.

**Comment by fellinga** [comment]
Well... it shouldn't be a big issue to replace the local variable, that currently holds the timers, with the nodes context. That way users with unmodified contextStorage settings wouldn't notice any differences and users (like you) with a contextStorage/localfilesystem would not have to save separately. 

I am going to take a deeper look at it this week and let you know as soon as I know more.

**Comment by SergiuToporjinschi** [comment]
I've done it like this, to be honest, because I can see what is the status in context tab :D

**Comment by fellinga** [comment]
1.7.0 now stores everything within the nodes context - it should be available on npm soon! I'd appreciate  your feedback!
