### ISSUE TITLE
Not accounting for DST? 

### ISSUE THREAD

**Issue by MatthewCroughan** [fellinga/node-red-contrib-ui-time-scheduler#3]
In Britain, DST just ended.

# 1

![image](https://user-images.githubusercontent.com/26458780/97392228-286af480-18d9-11eb-82be-16f40080f9b7.png)

Payload:
`{"schedule":{"_msgid":"26a29129.6accee","topic":"","payload":"{\"timers\":[{\"starttime\":17160000,\"endtime\":17460000,\"days\":[0,0,0,1,0,0,0]}]}"}}`

# 2

![image](https://user-images.githubusercontent.com/26458780/97392281-48021d00-18d9-11eb-982c-f09b22323c74.png)

`{"schedule":{"_msgid":"26a29129.6accee","topic":"","payload":"{\"timers\":[{\"starttime\":13560000,\"endtime\":17460000,\"days\":[0,0,0,1,0,0,0]}]}"}}`

At the time of writing, it is 4AM. When the clock hits 4:46 on my computer, and example # 2 is set, this node does not emit `true` as expected.

However, when example # 1 is set, and my clock hits 4:46, the node *does* begin to emit true. The node is an hour ahead of my current system time. The system running node-red reports the following via `date`.

```
bash-4.4$ date
Wed Oct 28 04:56:25 UTC 2020
```

**Comment by fellinga** [comment]
Hey Matthew,

could you add the code provided in this comment:
https://github.com/fellinga/node-red-contrib-ui-time-scheduler/issues/1#issuecomment-699034882

to your flow and compare it to your to your node-red&local time?

**Comment by MatthewCroughan** [comment]
@fellinga It indeed outputs the correct local time. 
![image](https://user-images.githubusercontent.com/26458780/97404117-7ab61080-18ed-11eb-8ced-a2a39e723779.png)

**Comment by MatthewCroughan** [comment]
My laptop's current local time is:
```
matthew@thinkpad ~ $ date
Wed 28 Oct 07:16:37 GMT 2020
```

**Comment by fellinga** [comment]
Are you using docker to run node-red?

**Comment by MatthewCroughan** [comment]
@fellinga Yes, I am.

**Comment by fellinga** [comment]
Okay this must be somehow related to docker. Please try the following:

Get the docker id:
`docker ps`
then get the time for the container (replace [container id] with your id):
`docker exec -it [container id] date`

Does it match with your host?

**Comment by MatthewCroughan** [comment]
@fellinga I believe I already gave you this output at the bottom of the opening issue message :smile: 

## My laptop
```

matthew@thinkpad ~ $ date
Fri 30 Oct 02:15:25 GMT 2020
```

## My laptop (running docker)

```
matthew@thinkpad ~ $ docker run -it alpine sh
/ # date
Fri Oct 30 02:15:42 UTC 2020
```

## Node Red container in Docker on Pi

```
bash-4.4$ date
Fri Oct 30 02:16:07 UTC 2020
```

**Comment by MatthewCroughan** [comment]
@fellinga 

I spoke too soon. Instead, I found out more about the nature of this bug.

I think this is best demonstrated with a video, so I made one. 
https://youtu.be/RWniXdq-oZ0

You can see that this bug is entirely reproducible. All you have to do is:
1. Set the time to an expected time to trigger
2. See that it does not trigger
3. Set the time 1 hour ahead of when you expect it to trigger
4. See that it does trigger
5. Try to set it back to the expected trigger time
6. See that the value is still true
7. Set below expected trigger time
8. See that the value does become `false`

This is definitely an odd bug. Any ideas? :smile:

**Comment by MatthewCroughan** [comment]
This image also shows you all that you need to see. It does not work. 

![image](https://user-images.githubusercontent.com/26458780/97744531-50c44000-1adf-11eb-83ba-3757c88df23c.png)

**Comment by fellinga** [comment]
I installed a fresh copy of Ubuntu (VirtualBox), Docker and Portainer to test this issue. I had to add an environment variable (name: TZ, value: Europe/Vienna) to the docker container so that the container has the same time as my docker host and it works perfectly fine.

Could you try what adding TZ=Europe/London as environment variable to your Docker container does?
Also, did you restart your pi/container since DST ended?

**Comment by fellinga** [comment]
Please checkout https://github.com/fellinga/node-red-contrib-ui-time-scheduler/commit/668738eb70f35969143a1248fb0b88719614fcad it's a pretty big update which also seems to fix the time zone bug. The fix should apply to all newly created timers.
