### ISSUE TITLE
Gate mode

### ISSUE THREAD

**Issue by gojkgojk** [fellinga/node-red-contrib-ui-time-scheduler#31]
Hi,

Thanks for the node and all of your work. I wanted to suggest adding a new mode, something along the lines of a "gate" mode. I've often had asynchronous messages arrive in my flows and needed to determine whether they should be allowed to trigger an action based on the current date/time. Maybe a solution would be to connect such inputs to your node to test whether they should pass or not. 

Thanks,
Jerry

**Comment by fellinga** [comment]
Hi @gojkgojk ,

you are very welcome!

I am not sure if I understand the use case correctly. So, do you want to decide if a value passes through a gate or not depending on what is currently configured within the ui-time-scheduler?
If that is the case then two simple function nodes should do the trick pretty easily I think. Could you try the following flow and see if that would work for you?

`[{"id":"e98bb82.7f9e048","type":"ui_time_scheduler","z":"96ef4fcc.950c6","group":"8ef567fd.b3a0f8","name":"","startDay":0,"refresh":60,"devices":["Device 1"],"onlySendChange":false,"customPayload":false,"eventMode":false,"eventOptions":[],"sendTopic":false,"lat":"","lon":"","outputs":2,"order":2,"width":0,"height":0,"x":610,"y":320,"wires":[[],["ff9254cf.cc4718"]]},{"id":"ff9254cf.cc4718","type":"function","z":"96ef4fcc.950c6","name":"GateSetter","func":"flow.set(\"somevariablename\", msg.payload);\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":830,"y":340,"wires":[[]]},{"id":"1ecbd29e.7ccfbd","type":"inject","z":"96ef4fcc.950c6","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":630,"y":380,"wires":[["389e9596.92345a"]]},{"id":"389e9596.92345a","type":"function","z":"96ef4fcc.950c6","name":"Gate","func":"if (flow.get(\"somevariablename\") === true) {\n    return msg;\n}","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":810,"y":380,"wires":[["932fe981.e7a868"]]},{"id":"932fe981.e7a868","type":"debug","z":"96ef4fcc.950c6","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1010,"y":380,"wires":[]},{"id":"8ef567fd.b3a0f8","type":"ui_group","name":"Cards","tab":"26840691.8b387a","order":3,"disp":false,"width":"6","collapse":false},{"id":"26840691.8b387a","type":"ui_tab","name":"Dashboard","icon":"dashboard","order":1,"disabled":false,"hidden":false}]`

**Comment by gojkgojk** [comment]
Yes, that's what I was looking for. I didn't think of that simple idea.

Thank you!

**Comment by fellinga** [comment]
No problem, glad I could help and feel free to contact me anytime if you need anything else.

BTW: 1.8.0 added configurable event options, a customizable dropdown for events so to say. I think you used the node for controlling your HVAC system - thought this could be useful for you.

**Comment by gojkgojk** [comment]
Yes, that was ideal. Much appreciated.

Jerry
