### ISSUE TITLE
Dashboard using httproot, without 'ui' path, causes sheduler not to work

### ISSUE THREAD

**Issue by LiskaMatej** [fellinga/node-red-contrib-ui-time-scheduler#32]
Hello @fellinga, I'm using dashboard with http root path only (http://mydomain.com:1880/) - without 'ui' (e.g.: http://mydomain.com:1880/ui ). And sheduler does not work when using only root path. 

Settings can be found in settings.js of node-red (line 118).

**I've hotfixed it this way** - 

In time-scheduler.js - replaced:
```javascript
	const uiPath = ((RED.settings.ui || {}).path) || 'ui';
	let nodePath = '/' + uiPath + '/time-scheduler/getNode/:nodeId';
	nodePath = nodePath.replace(/\/+/g, '/');
```

with:
```javascript
	if (RED.settings.ui === undefined || RED.settings.ui.path !== "") {
		const uiPath = (RED.settings.ui || {}).path || 'ui';
		var nodePath = '/' + uiPath + '/time-scheduler/getNode/:nodeId';
	} else {
		//case when dashboard is used in root path e.g.: http://mydomain:1880/
		var nodePath = '/time-scheduler/getNode/:nodeId';
	}	
	nodePath = nodePath.replace(/\/+/g, '/');
```

Thanks and keep up the good work.

**Comment by fellinga** [comment]
Thank for your feedback!
I am running two node-red instances whose dashboards are both available through www.domain.com:1880/ and the scheduler works fine. Please let me see line 118 of your settings.js file.

**Comment by LiskaMatej** [comment]
![image](https://user-images.githubusercontent.com/9565371/115383317-f6768300-a1d5-11eb-9093-564ea1bdd0d5.png)

Thx. for your fast reply.

**Comment by LiskaMatej** [comment]
Issue is that, sheduler is shown but I'm unable to save or push config, it won't keep it.
Running latest NR 1.3.2, docker on windows, also same problem on clean install without docker on rpi :-O

**Comment by fellinga** [comment]
I see, it should work with **_ui: { path: "/" }_** though. Could you try this as well?

Anyway.. definitely needs a fix, I'll try to push one this evening.

**Comment by LiskaMatej** [comment]
ui: { path: "/" } works allright! :-)

Thank you.
