### ISSUE TITLE
How to use getStatus?

### ISSUE THREAD

**Issue by anilsagar** [fellinga/node-red-contrib-ui-time-scheduler#38]
Can you pls share an example on how to use getStatus in an input msg to the scheduler node? There is no info available on the same.

**Comment by fellinga** [comment]
Hi @anilsagar ,

sure. You only need to send a message with a key "getStatus" to the nodes input. The value can be empty or any other value - only the key is of importance here. Here is an example: 

![getStatus](https://user-images.githubusercontent.com/26927863/119219506-40f56300-bae6-11eb-8a5d-4730d1b5758a.jpg)

If you want to trigger this from a function node for example, then it would look like this:

![getStatusFunc](https://user-images.githubusercontent.com/26927863/119219609-aea18f00-bae6-11eb-97b5-eb80f6b9c80a.jpg)


Please let me know if this helps!

**Comment by anilsagar** [comment]
Many thanks. That worked.
