### ISSUE TITLE
[Enhancement] 

### ISSUE THREAD

**Issue by WhiteLionATX** [fellinga/node-red-contrib-ui-time-scheduler#39]

**Comment by WhiteLionATX** [comment]
Please add 24h als alternative to AM & PM. 
My wife is getting crazy with current model.
Thx!

**Comment by fellinga** [comment]
The time scheduler only uses a time input field which auto detects the correct display properties by your browser settings.
Try opening https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time and see how your device renders the time input - it will be just like the time scheduler does. If you want to change that, you need to change your browser settings.

Please let me know if this helps!

**Comment by WhiteLionATX** [comment]
Thank you for your fast reply. It worked like a charme !
