### ISSUE TITLE
[Enhancement] SUNEVENTS as start/stop time

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [fellinga/node-red-contrib-ui-time-scheduler#40]
Really love your node and have changed all my timer related flows to this node.

I have a few use-cased where I have to over-write your scheduler with SUNEVENTS ([using this node](node-red-contrib-sunevents)) but it is limited in regards of scheduling based on different days.

I'm aware that your scheduling is based on CRON but so you see a chance to include SUNEVENTS as Start/Stop time in your scheduler?

thanks for considering

**Comment by fellinga** [comment]
Hi @xX-Nexus-Xx ,

I am not sure if I understand your question -my timer is not based on CRON and it already does support sun-events. Could you explain your question again?

**Comment by xX-Nexus-Xx** [comment]
Sorry, for the confusion.

For example, I have a light schedule weekdays from 5pm to midnight to switch on my motion detection and light activation.

**Comment by fellinga** [comment]
Okay, so you want to be able to either:
- have a static start time and a sun event as end time 
- have a sun event as start time and a static end time 

Does [this ](https://github.com/fellinga/node-red-contrib-ui-time-scheduler/issues/33)answer your question?

**Comment by xX-Nexus-Xx** [comment]
Ideally any combination

- have a static start time and a sun event as end time
- have a sun event as start time and a static end time
- have a sun event as start time and sun event end time

I have seen that other [thread](https://github.com/fellinga/node-red-contrib-ui-time-scheduler/issues/33) and I'm already working as well with event mode, however would like to  have the SUNEVENTS.

Alternatively, I'm currently testing to overwrite an event with todays/tomorrows SUNEVENT time. 

Example:
- Timer is set 6pm to 8pm
- get SUNSET time from other node (e.g. 5.55pm)
- overwrite 6pm time witn SUNSET time (5.55pm)

Unfortunately it does not work yet :(

**Comment by fellinga** [comment]
I am honestly a little confused. Like I said in my first answer to this thread, sun events are already supported.

![1](https://user-images.githubusercontent.com/26927863/124066178-8176c380-da38-11eb-9da6-268e1c8b557d.jpg)
![2](https://user-images.githubusercontent.com/26927863/124066183-83408700-da38-11eb-84d2-d4b5e3101125.jpg)

Did you set Longitude and Latitude in the nodes settings?

**Comment by xX-Nexus-Xx** [comment]
Sorry, my bad .. I totally overlooked the SUN symbol and functionality.. this will work for me!

At moment it only shows SUNSET/SUNRISE .. is it possible to have other events as well
<html>
<body>


sunrise | top edge of the sun appears on the horizon (-0.833°)
-- | --
sunriseEnd | sunrise end | bottom edge of the sun touches the horizon (-0.3°)
morningGoldenHourEnd | morning golden hour ends | when the sun is 6 degrees above the horizon (6°)
solarNoon | solar noon | sun is at its highest position
eveningGoldenHourStart | evening golden hour start | when the sun is 6 degrees above the horizon (6°)
sunsetStart | sunset start | bottom edge of the sun touches the horizon (-0.3°)
sunset | sunset | civil twilight starts, sun disappears below the horizon (-0.833°)
civilDusk | civil dusk / golden hour end | civil twilight and golden hour ends, nautical twilight starts (-6°)
nauticalDusk | nautical dusk | nautical twilight ends, astronomical twilight starts (-12°)
nightStart | astronomical dusk / night start | astronomical twilight ends, night starts (-18°)
nadir | solar midnight | when the sun is closest to nadir and the night is equidistant from dusk and dawn


</body>
</html>

**Comment by fellinga** [comment]
#44 added more sun events for everyone using event mode.
