### ISSUE TITLE
[Enhancement] Set Device Names via msg.something

### ISSUE THREAD

**Issue by jodelkoenig** [fellinga/node-red-contrib-ui-time-scheduler#48]
Hey fellinga, 

this is a really nice extension to my palette. Helps to conveniently control some devices in my house. Thanks for your contribution!

I was wondering whether it would be possible to allow the setting of device names via an input message, like f.e. msg.device1 or so. The names of my devices are rather short. Which leaves a lot of "real estate" on the dashboard next to the device name without any information. And I am inclined to fill it with something useful :)

Please treat this as an idea and not a request. I am already really really happy with your contribution as is 👍

**Comment by fellinga** [comment]
Hi @jodelkoenig,

this idea has come up (in different variations) a couple of times now but unfortunately it is not easily doable without breaking backwards compatibility. It is not off the table but I am going to close this issue with a reference to #28. If it happens then very likely in a v2.x.x.
