### ISSUE TITLE
[FR] Choose Context Storage

### ISSUE THREAD

**Issue by Sineos** [fellinga/node-red-contrib-ui-time-scheduler#49]
Many thanks for this contribution. This is really a missing link between all the timer and schedule nodes and the dashboard.

I'm using different context storage options in my projects. Default is typically a non-persistent storage (e.g. for runtime data) and for certain tasks, I'm also using persistent storage (e.g. for settings).

Would you consider to add a setting to choose the storage so that it is possible to point it to a persistent storage? Many thanks for considering in advance.

**Comment by fellinga** [comment]
Thank you for your feedback. I was able to start developing the requested change today and I am planning to release an update soon.

Could you provide your context storage configuration from your settings.js file as an additional test case?

**Comment by Sineos** [comment]
Many thanks for your ultra fast response. Appreciated!

As requested:

```
	"contextStorage": {
		"default": {
			"module": "memory"
		},
		"file": {
			"module": "localfilesystem",
			"config": {
				"dir": "/media/usb0/context/",
				"flushInterval": 30
			}
		}
	},
```

**Comment by fellinga** [comment]
1.15.0 should be available via the palette manager soon.
I would be very grateful if you could do a few tests!

**Comment by Sineos** [comment]
Works as expected. Many thanks for your great support! 👍
