### ISSUE TITLE
[FR] Add Set-Point

### ISSUE THREAD

**Issue by Sineos** [fellinga/node-red-contrib-ui-time-scheduler#50]
I really love this node and without wanting to come over as demanding:

Adding a setpoint (== payload to send) associated with each schedule would be simply amazing. This would turn it into a "Swiss army knife", e.g. for a heating system to send different temperature targets at various week-days or according to day's time.

**Comment by fellinga** [comment]
I am not sure if this is what you want but have you tried to activate the "Event Mode"? With Event Mode enabled you can create a list of events that the user can select at the front end.
![eventmode](https://user-images.githubusercontent.com/26927863/127488909-07b79ac2-492d-4111-b0cd-0931f072b51a.png)

You can also check "User Events" if you want to enter the value directly from the front end.
![eventmodeuserevents](https://user-images.githubusercontent.com/26927863/127488977-509571d2-33f0-49ea-a837-9914c4ca05c8.png)

![custompayload](https://user-images.githubusercontent.com/26927863/127489203-d607ee30-3625-42ea-a6a4-6bcc4f1e8394.png)

**Comment by Sineos** [comment]
How could I have missed this?!? Thanks for pointing me to this. Love it!
