### ISSUE TITLE
Wrong Translation in node-red-contrib-ui-time-scheduler/locales/de/time-scheduler.json

### ISSUE THREAD

**Issue by XneddyX** [fellinga/node-red-contrib-ui-time-scheduler#51]
Line 68 "sunsetStart": "Beginn Sonnenaufgang"
must be:
"sunsetStart": "Beginn Sonnenuntergang"

**Comment by fellinga** [comment]
Just updated the source, the change will be included in the next release.

Thanks for pointing this out!
