### ISSUE TITLE
Time intervals 

### ISSUE THREAD

**Issue by tatuiot** [fellinga/node-red-contrib-ui-time-scheduler#53]
I cannot call an issue , really.
Hi, I came across this solution, but I still need if its possible to do the following.
Start from 10 AM to 6 PM , but turn on for 1 min and turn off for 5 mins (as an example ) is it possible to do this ?
thanks a lot

**Comment by fellinga** [comment]
Hi @tatuiot, 

you can create as many timers as you want, therefore you could do something like that:
![1](https://user-images.githubusercontent.com/26927863/129959419-bb96557c-01c4-41c3-899b-6803924360bb.jpg)

There is no automation though, so you have to create every timer manually. Is this what you wanted to know?

**Comment by tatuiot** [comment]
I see. yes, but I wanted to avoid the user to go and create 600 timers (because there are 12 devices)  ... but at the end is fine.
May be an enhacement could be to create a repetitive on/off timer inside  an schedule...

**Comment by fellinga** [comment]
You can inject timers via a msg.payload, for example:
10:00AM to 10:01AM would be: {"starttime":1629273600000,"days":[1,1,1,1,1,1,1],"output":"0","endtime":1629273660000}
10:06AM to 10:07AM would be: {"starttime":1629273960000,"days":[1,1,1,1,1,1,1],"output":"0","endtime":1629274020000}
10:12AM to 10:13AM would be: {"starttime":1629274320000,"days":[1,1,1,1,1,1,1],"output":"0","endtime":1629274380000}

So there is a possibility to generate them somewhere else and then inject them into the nodes input. As you can see from the example you only need to generate them for the first device and for every other device you just need to modify the "output" value.

The full payload for the example above would be:

"{"timers":[{"starttime":1629273600000,"days":[1,1,1,1,1,1,1],"output":"0","endtime":1629273660000},{"starttime":1629273960000,"days":[1,1,1,1,1,1,1],"output":"0","endtime":1629274020000},{"starttime":1629274320000,"days":[1,1,1,1,1,1,1],"output":"0","endtime":1629274380000}],"settings":{}}"

**Comment by tatuiot** [comment]
Nice one !!! thanks a lot... that would work, I´ll give it a try... thanks a lot

**Comment by tatuiot** [comment]
Hi Sorry, but I have been fighting with this... no success. What am I doing wrong?

![image](https://user-images.githubusercontent.com/62341203/129984115-90b7445a-3ff3-404a-91a5-637b7ba4d93b.png)

This is my payload inject JSON string

![image](https://user-images.githubusercontent.com/62341203/129984182-8a9e19c6-64f9-4aef-a7c7-0cad4347da92.png)

and this is the object taken from the output , which I assume is properly composed. 

"{"timers":[{"starttime":1629284400000,"days":[1,1,1,1,1,1,1],"output":"0","event":true},{"starttime":1629327600000,"days":[1,1,1,1,1,1,1],"output":"0","event":false}],"settings":{"disabledDevices":[]}}"

I also tried to setup as a JSON. no succes either... I am lost. sorry about this.

**Comment by fellinga** [comment]
Your string is valid (for the event mode), you only need to remove the first and last quotation mark. 
![1](https://user-images.githubusercontent.com/26927863/130017456-6ff6484b-ca91-4f40-94d9-617ffb1ea0ff.png)

**Comment by tatuiot** [comment]
oh my god... I feel so fool...  thanks a lot, yes it works... thanks so much

**Comment by fellinga** [comment]
You are welcome!
If you need anything else, let me know!
