### ISSUE TITLE
Start today, finish tomorrow!

### ISSUE THREAD

**Issue by servim** [fellinga/node-red-contrib-ui-time-scheduler#54]
Very cool schedule!
I would like to be able to add something like this with one schedule:
21: 00-07: 00
Instead of this:
21: 00-00: 00
00: 00-07: 00
Thanks!

**Comment by fellinga** [comment]
Hi servim,

there has been a reason in the past why I did not allow this but it should be okay by now.
1.16.0 was pushed to NPM and should be available via the palette manager soon.
