### ISSUE TITLE
Enhancement - manual control button for on, disable button for off 

### ISSUE THREAD

**Issue by RudyFiero** [fellinga/node-red-contrib-ui-time-scheduler#56]
Thanks for this node.  I am happy to have this interface. I thought it was ridiculous that someone would have to go to the admin page to modify schedules. (with other schedulers) Your node solves this problem. 

In my Node Red system I have a light turned on at 5:20 am along with an internet radio, Mondays to Friday. No action on the weekend. The problem I have is that when there is a long weekend I would like to easily disable a normally scheduled event. I would rather sleep in than get woken up by the light and music. 

I can see how I could go in and modify the schedule, but that is a number of steps and I will again have to restore the normal settings after the day had passed, or until the timer is reactivated. (I just thought of vacation days where I would be off for a number of days)

And the manual turn on button could be helpful for some although it is not as significant as being able to disable the timer.

Ideally I would like to see the disable button on the description bar.

**Comment by fellinga** [comment]
Hi @RudyFiero ,

thank you for your feedback, it is always nice to hear about how people use the scheduler!
The scheduler already provides the functionality to disable a device or a single timer (until it gets turned on again).

The button that disabled the whole device is located next to the add button:
![time-scheduler](https://user-images.githubusercontent.com/26927863/134787473-2e5b5bbf-feef-4579-94cd-235f7036ab0a.jpg)

If it was clicked all the timers for this specific device are out of order. 

The same button can be found by clicking an existing timer (where you would edit the timer) if this button is activated then only this specific item is disabled.
![time-scheduler](https://user-images.githubusercontent.com/26927863/134787571-2fbfd1c6-ed56-4d96-bfb4-68ffeed5d23a.png)

Please let me know if this helps!

**Comment by RudyFiero** [comment]
LOL
So the clock is more than just a pretty face. 

Once again. Thank you for this useful node.
