### ISSUE TITLE
Timespan enhancement request

### ISSUE THREAD

**Issue by GwelforBodad** [fellinga/node-red-contrib-ui-time-scheduler#58]
Please will you consider the following enhancement requests, if feasible?
1. Add further times to the custom list such as astronomical dawn, nautical dawn, civil dawn and the same for the other end of the day?
2.  Enable the custom list to be used in the timespan mode?

I assume that as the year progresses, your node updates the custom times as they change.  Does it do this daily?

I'm looking specifically to be able to control my outside lights every morning and evening so that they come on at say 6.30am and switch off at civil dawn and switch on at civil sunset and off at 11pm.  However, where I live, this would work well on a schedule in the winter but in the summer, civil dawn is before 6.30am although sunset would be before 11pm.  However, there are latitudes where it stays light all the time during summer.  So how would I create a schedule which wouldn't turn on the lights at 6.30 in the morning if the civil dawn had already passed?  If this isn't available already, it's not an issue.  I was going to manage all this using the rdmtc [sun position node](https://github.com/rdmtc/node-red-contrib-sun-position/wiki/sun-position) but your ui interface is the thing that makes your node so useful.  Thanks

**Comment by cheechie** [comment]
This would be great!

**Comment by fellinga** [comment]
Hi @GwelforBodad,

1. The ui-time-scheduler depends on https://www.npmjs.com/package/suncalc and it currently offers all the options that suncalc offers. You could open an issue there, it will be available within the ui time scheduler node once they have published that change.

2. now works with 1.17.0
