### ISSUE TITLE
Dashboard crashes

### ISSUE THREAD

**Issue by postolis** [fellinga/node-red-contrib-ui-time-scheduler#59]
Hey, im trying to create a iot garden controller and found your node. The first time i installed it worked like a charm but then i stopped the node-red server and the ui crashed.If i uninstall nodejs and node-red and install them again it fixes the problem until i stop the server again.Im using the latest versions of node-red nodejs and ui time scheduler, im also running the server locally on windows 10
![Screenshot_2](https://user-images.githubusercontent.com/92605197/137547294-0939cbb6-672c-4b56-9a7d-21ba1c91e8d4.png)
![Screenshot_1](https://user-images.githubusercontent.com/92605197/137547306-3ae54491-fd8b-483d-91c1-24ff59b4c8fb.png)

.

**Comment by fellinga** [comment]
hi @postolis,

the UI can't work without the server. If you want to have access to the UI and all the UI nodes you have to have the server running.

Why do you want to stop the server?

**Comment by postolis** [comment]
Added another switch node but the ui didnt came back , when i restarted without the ui scheduler enabled everything came back back plus the new switch i added.Here is a screenshot with the flow and theme settings.
![Screenshot_4](https://user-images.githubusercontent.com/92605197/137588311-ee43a094-88d0-4f0f-8e5c-a1f79a57cd2d.png)
![Screenshot_5](https://user-images.githubusercontent.com/92605197/137588342-e933a501-ff7f-4435-8e55-e18246ad5e05.png)

![Screenshot_6](https://user-images.githubusercontent.com/92605197/137588343-457099b1-0c05-4aaa-87ff-2339c5d5b6ad.png)

**Comment by fellinga** [comment]
Please post the output of the node-red-log from the last restart with the UI scheduler enabled here.

**Comment by postolis** [comment]
The first screenshot is with the scheduler disabled (ui working normally)
second screenshot is with the scheduler enabled (only scheduler is visible and theme changed to default)+
third screenshot is enabling scheduler when ui worked normally(ui page didnt refreshed it self when deployed and showed everything exept the scheduler.When i refreshed the page only the scheduler was visible)

![Screenshot_7](https://user-images.githubusercontent.com/92605197/137590021-48ee1d3e-5297-46d6-a393-13c1b9207572.png)

![Screenshot_8](https://user-images.githubusercontent.com/92605197/137590029-554575d7-b01d-4b6b-a2f5-71df9c7e65b0.png)

![Screenshot_9](https://user-images.githubusercontent.com/92605197/137590032-cac3b5fb-8bf2-483b-9056-d975462fe9fb.png)

The flow : 

[flows.txt](https://github.com/fellinga/node-red-contrib-ui-time-scheduler/files/7357660/flows.txt)

**Comment by fellinga** [comment]
I tried your flow on different systems - ubuntu local install (nodejs 14) as well locally on Windows 10 with Nodejs 16.13 and node-red 2.1.3 and rebooting works just fine. Did you try to run it in Docker yet?

**Comment by postolis** [comment]
Hey, no it didnt work in Docker but a week ago i upgraded my windows to 11 also upgraded node-dashboard and the ui-scheduler and since then everything runs smoothly.Been testing with restoring the schedules, stopping the server then starting it again not a single problem!
