### ISSUE TITLE
it is not issues, just let me know... how can i change language...  

### ISSUE THREAD

**Issue by DONGILBAE** [fellinga/node-red-contrib-ui-time-scheduler#67]
It's great for me. to control schedule. 
I have a question, even i am stupid, please let me know. 
I am a korean and want to change korean language. 
In your folder i found locale folder( include de, US json ) . 
normally, when i create new language folder and change language code , it can be change new language. 
But i can not find change language option.... 

Yes,  if i reprogram on javascript( depend on your source code ), i can change language( ex, use US json code change ) 
But i want to follow your programming rule, So i want to know how can i change language? if i create new language folder..
or can i reprogramming on your source code?

**Comment by fellinga** [comment]
Hi @DONGILBAE,

thanks for reaching out to me. I had a similar question recently which I answered here: https://github.com/fellinga/node-red-contrib-ui-time-scheduler/issues/66 does this help?

**Comment by DONGILBAE** [comment]
Thank you for your kindly answer... I guessed maybe setting.js.... and you gave me correct answer to me. thanks again... it is working well.... If you don't mind, may i send korean json code? I hope it is more upgrade for your good project..

**Comment by DONGILBAE** [comment]
[korean_locate.zip](https://github.com/fellinga/node-red-contrib-ui-time-scheduler/files/7600100/korean_locate.zip)

**Comment by fellinga** [comment]
No problem and thank you for the translations!
Please let me know if you need anything else.
