### ISSUE TITLE
Time is in AM/PM but I prefere 24h format

### ISSUE THREAD

**Issue by rothestar** [fellinga/node-red-contrib-ui-time-scheduler#71]
I dont know if it is the node or the setup of the instalation of the raspberry pi, but perhaps you know what is going on.

It is installed via this installation https://github.com/gcgarner/IOTstack

But when it is in the default view at the node red dashboard the time is shown i 24h format, but when i click to alter the time it is in 12h format any idea??

Hest regards
Henrik

**Comment by fellinga** [comment]
The time input field is a standard HTML control, it shows 24/12 hour clock based on your browser language, it should match with whatever you see here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time and you should be able to change that by adjusting the browser settings. you might also want to take a look at this issue: https://github.com/fellinga/node-red-contrib-ui-time-scheduler/issues/8

Please let me know if this helps!

**Comment by mongojarle** [comment]
The node does not respect my browser settings. Browser (vivaldi) and computer (win10) is showing 24 hour format, and everything else in nodered as well, except this node.
Could be something that I have missed.

**Comment by mongojarle** [comment]
![timepick](https://user-images.githubusercontent.com/41956509/153547907-8adf6844-aa79-498f-9642-b7c10606495a.png)

![timesettings](https://user-images.githubusercontent.com/41956509/153548127-7a0c3a11-7b7d-4ab5-83b9-38819e5ff863.png)

I just noticed that nodered is also showing 12-hour clock, but everywhere else in my browser it is 24-hour.
Nodered runs on a NAS that is set to 24-hour, and my nodered docker container enviromental vaiable TZ=Europe/Oslo. Will investigate.
Anyway not a problem with this node.

**Comment by fellinga** [comment]
The backend (node red server) should not have anything to do with how the browser displays the time input. Simplest way to test would be to create a index.html file with the content `<input type="time" id="appt" name="appt">` on your local computer and open that with your favorite browser. After that you can adjust settings until it show the time correctly.

I am going to close this issue, let me know if you need anything else!

**Comment by mongojarle** [comment]
Thanks for your help!
Yeah, this is a issue with my browser, Vivaldi. The time picker are showing AM/PM, but the schedule is showing 24-hour clock.
![timepicker](https://user-images.githubusercontent.com/41956509/153751296-ccc0aa4f-d5a2-4905-abc3-e48ef3c7d1db.gif)
