### ISSUE TITLE
wrong icons

### ISSUE THREAD

**Issue by przemekacx** [fellinga/node-red-contrib-ui-time-scheduler#76]
Hi,
I have "fa icons 4.7" installed and they work for other flows, but they are not visible in UI Scheduler, what could be wrong?
![image](https://user-images.githubusercontent.com/92912562/162911238-1e27f6d2-83d7-42e9-8be9-baf95acd0789.png)
![image](https://user-images.githubusercontent.com/92912562/162911249-2f9ee13d-00c9-411c-b679-bec784a3c880.png)
For other flows it is OK:
![image](https://user-images.githubusercontent.com/92912562/162911440-cbfe5c4b-c770-4eca-9506-5d43679c0a3e.png)

**Comment by fellinga** [comment]
Hi @przemekacx,

without having a deeper look at it could you tell me how you installed the icons?

**Comment by przemekacx** [comment]
I used this manual: [Paul-Reed](https://github.com/Paul-Reed/weather-icons) and it is working as it was expected. I use also this icons for dynamically changing buttons with <i class="wi wi-day-sunny"></i> code in payload, so all of them should be visible.
Can I present or check something?

**Comment by fellinga** [comment]
The ui time scheduler uses standard angular material icons, like this:
`<md-icon> filter_alt </md-icon>`

so there is not much that I can do or change.

References:
https://material.angularjs.org/1.2.5/api/directive/mdIcon 
https://fonts.google.com/icons?selected=Material+Icons


The link to Paul's project explicitly says: "DO NOT USE - SEE [WEATHER-ICONS-LITE](https://github.com/Paul-Reed/weather-icons-lite) WHICH IS MERGED INTO NODE-RED CORE". If it was merged into node-red then these icons should work out of the box already, can you undo the changes and see if these icons still work?

**Comment by przemekacx** [comment]
OK, thanks, I will check this.

**Comment by fellinga** [comment]
Good to know, thanks for letting me know. I am going to close this issue, let me know if you need anything else!
