### ISSUE TITLE
Seeing AM/PM format hours instead of 24 hour format in dropdown option on Samsung Android device

### ISSUE THREAD

**Issue by mojgithub** [fellinga/node-red-contrib-ui-time-scheduler#79]
Hi

So i have a problem with seeing AM/PM format hours instead of 24 hour format ONLY in dropdown option on Samsung Android device. On PC it looks ok. Check image from Android. It should have been 24 hour format everywhere.

![24format](https://user-images.githubusercontent.com/15635705/174468576-4e27a40d-2af1-49a1-bf2f-bce3adbeef3e.png)

**Comment by fellinga** [comment]
Hi @mojgithub ,

this is definitely not a bug - it is a browser setting.
Please review this isse: #71  post it will help you understand why your Android device displays it this way.

**Comment by mojgithub** [comment]
> Hi @mojgithub ,
> 
> this is definitely not a bug - it is a browser setting. Please review this issue: #71 it will help you understand why your Android device displays it this way.

Tnx. I have changed on Android Chrome language from English US to English Britain and shows 24 format.
