### ISSUE TITLE
Time setting not as shown on your page.

### ISSUE THREAD

**Issue by Just-another-pleb** [fellinga/node-red-contrib-ui-time-scheduler#8]
https://flows.nodered.org/node/node-red-contrib-ui-time-scheduler

Scroll down to where you show how to use the GUI.

The time shown doesn't match.

The GUI still has the AM/PM thing at the side of the time.

**Comment by fellinga** [comment]
The time input field is a standard HTML control, it shows 24/12 hour clock based on your browser language. 
A browser language English (United States) shows 12 hour clock (therefore with AM/PM), while English (United Kingdom) shows the 24 hour clock.

**Comment by Just-another-pleb** [comment]
Ok, but I don't see the association between having English (United States) makes it 12 hour format and English (United Kingdom) makes it 24 hour.

But thanks.

**Comment by Just-another-pleb** [comment]
Ok, but I don't see the association between having English (United States) makes it 12 hour format and English (United Kingdom) makes it 24 hour.

But thanks.

**Comment by Just-another-pleb** [comment]
I just went through finding how to change it from US to GB.

Restarted FF and I am still seeing the times in AM/PM on the GUI.

![Screenshot from 2020-11-23 20-53-01](https://user-images.githubusercontent.com/39888280/99948766-09735b80-2dce-11eb-8ba4-60ca4306b281.png)

![Screenshot from 2020-11-23 20-52-40](https://user-images.githubusercontent.com/39888280/99948767-09735b80-2dce-11eb-80c6-7e544e9d3905.png)

**Comment by fellinga** [comment]
Seems as if Firefox on Debian doesn't change the time format to 24h if English (UK) is selected (it does on Mint). Changing the Browser language to Spanish or German does definitely change the input to 24h. You can test different settings here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

Seems like as If Chrome handles that differently, I think it uses the operating system locale, maybe this would work for you.

As you can see the format shown only relies on the browser/operating system and is nothing that is in my hand (although I need to get rid of the trailing zeros (Firefox only).

**Comment by Just-another-pleb** [comment]
Again, sorry.  Ok, thanks.

It wasn't I was trying to "blame" you.  I am just asking.
