### ISSUE TITLE
[Enhancement] - Box height for multiple events; clock icon on/off side lines

### ISSUE THREAD

**Issue by mojgithub** [fellinga/node-red-contrib-ui-time-scheduler#80]
Hi

1) i would like to suggest adding a feature to dynamically change height of the box when having multiple events even if that means pushing other boxes down. Now there is a scroller and this is not ok. User should have an option in settings to force this behaviour. Add it near size option. Check screen
![meaning3](https://user-images.githubusercontent.com/15635705/174469751-31454411-2e12-43e1-b5ed-bd2f7e5e611c.png)

2) side red line when event or events are disabled?

if i disabled single event it get red side line. This is ok.
if i disable ALL events nothing happens i mean there is no side line? I suggest adding a big red line to all events.

![meaning1](https://user-images.githubusercontent.com/15635705/174469809-efefb150-cf8c-4899-a804-846c17295311.png)
![meaning2](https://user-images.githubusercontent.com/15635705/174469810-cb892f51-d566-43b1-8650-c9d97fb1d164.png)

**Comment by fellinga** [comment]
@mojgithub thanks for your feedback!

Unfortunately the node-red-dashboard framework does not allow dynamically changing box sizes. That means that I can not change the height of the scheduler during runtime. You can only change the box height in the node settings and that will be kept during the entire deploy.

![image](https://user-images.githubusercontent.com/26927863/174473197-ade4f1f6-9155-46c1-b95d-35f632866a9e.png)

I did correct the behavior of the red line though and already pushed the release, you should be able to download 1.17.1 in a few minutes!

Please let me know if I can help with anything else!

**Comment by mojgithub** [comment]
> I did correct the behavior of the red line though and already pushed the release, you should be able to download 1.17.1 in a few minutes!

It works! Tnx
