### ISSUE TITLE
hours:minutes:seconds instead of only hours:minutes in the scheduler

### ISSUE THREAD

**Issue by venumz** [fellinga/node-red-contrib-ui-time-scheduler#87]
Hello fellinga,
I have just started learning Node-Red, I have used Blynk before, but since the legacy app is not available anymore I am looking for alternatives.

You have created very nice node here, and is almost perfect for my hobbyist needs. Do you think that you could add in the future the option to have also seconds instead of only hours:minutes in the scheduler?

Thanks a lot and keep up the good work :)

**Comment by fellinga** [comment]
Hi @venumz,

the biggest issue on this topic is space. The ui-time-scheduler was made to be very compact and it would need a redesign to fit seconds into the current minimum width. I am going to port the app to dashboard2 once officially available and consider the feature request for that.

Thanks for your feedback.
