### ISSUE TITLE
When the minutes change, there is always a false

### ISSUE THREAD

**Issue by akofx** [fellinga/node-red-contrib-ui-time-scheduler#88]
My goal is to get exactly 1 true or false for the respective on / off events.
Ideally I would like to use the "Combined start-end view", so I selected the two switches "Send "from" messages only at the selected end time" & "Block messages until the value changes".
I only set the refresh time to 10 seconds for test purposes - to see if it works.
The result is surprising - that a false value is returned once for every minute change.
You can also see this very well if the two switches mentioned above are not selected - then in the "on phase" every minute there is a false value, then a true value again.
The problem is that this output is supposed to drive a relay with a beamer. Constantly switching the projector off and on again is not good for the lamp - apart from the fact that the projector cannot react that quickly. Please help.
LG Thomas
![202212030941_001](https://user-images.githubusercontent.com/119728605/205433037-31f66e6d-3611-48b7-9f13-d7df495203fe.png)
![202212030941_002](https://user-images.githubusercontent.com/119728605/205433038-a3403197-1689-4599-bc61-f973c764e689.png)
![202212030941_003](https://user-images.githubusercontent.com/119728605/205433039-23829512-d461-4dfc-b681-a64824033624.png)
![202212030941_004](https://user-images.githubusercontent.com/119728605/205433041-2000835e-021e-428e-841a-6b5042d7f0a7.png)

**Comment by fellinga** [comment]
Hi Thomas!

If you have testest with the attached screenshots then everything looks good. The debug 5 node appears two times in your log: once at 09:44 with true and once at 09:46 with false.

There is some other debug node (4) in between that sends the other falses.

![image](https://user-images.githubusercontent.com/26927863/205438016-904b7926-a86c-49ec-af35-858537b2f69a.png)

I've just tested it again and it works as excepted:
![image](https://user-images.githubusercontent.com/26927863/205438478-9fdeeec5-5eb5-4ea9-9eed-da9634beed34.png)

**Comment by akofx** [comment]
Dear fellinga

Thank you very much for your fast reply!

YES! You are absolutely right!
Shame on me - that was my fault!

Sorry about the circumstances!

Greetings from Austria
Thomas
