### ISSUE TITLE
Change device names from input

### ISSUE THREAD

**Issue by Tonyb71** [fellinga/node-red-contrib-ui-time-scheduler#89]
Happy new year,

First of all, congratulations for the nice node, great job.

Its not really an issue, i just wondering if there is already a way to change dynamically the device names already created.

Using the input
Is there any command that allows you to change the name of each device?
For example: similar to msg.enableDevice + identify the device name or index to be enabled.
Sending msg.name_device1 or  msg.id1 or something like that + the new name.

Many thanks

Tony

**Comment by tjd999hotmail** [comment]
> Happy new year,
> 
> First of all, congratulations for the nice node, great job.
> 
> Its not really an issue, i just wondering if there is already a way to change dynamically the device names already created.
> 
> Using the input Is there any command that allows you to change the name of each device? For example: similar to msg.enableDevice + identify the device name or index to be enabled. Sending msg.name_device1 or msg.id1 or something like that + the new name.
> 
> Many thanks
> 
> Tony

Hi, 
I agree that your request to programatically change the device names is definitely needed.  It is an absolute must to change/add/subtract device names so you can modify the function of the scheduler with context data which is what I want to do. In my case, several neighbors want to use my program (they are not programmers) to augment their pool automation efforts.  Frankly, I am surprised that this was not asked for before now.

**Comment by fellinga** [comment]
This idea has come up (in different variations) a couple of times now but unfortunately it is not easily doable without breaking backwards compatibility. It is not off the table but I am going to close this issue with a reference to https://github.com/fellinga/node-red-contrib-ui-time-scheduler/issues/28.
