### ISSUE TITLE
Please tidy up the name used.

### ISSUE THREAD

**Issue by Just-another-pleb** [fellinga/node-red-contrib-ui-time-scheduler#91]
I was recently updating my node list.
I saw this `node-red-contrib-ui-time-scheduler` update available.
Oh.   Ok.....   Brain failure and so I thought I would search for it.
NOT FOUND.

After a lot of messing around it is called
`ui_time_scheduler`

It would be nice is the `-` were kept and not replaced with `_`.
It really makes searching for the node annoying.

No, not critical.   But it seems inconsistent with the use of `-` and `_` interchangeably.

**Comment by fellinga** [comment]
That would possible break existing installations therefore I won't change it now.
I will consider the change when I port the node to dashboard2.
