### ISSUE TITLE
cannot delete timers

### ISSUE THREAD

**Issue by simon276** [fellinga/node-red-contrib-ui-time-scheduler#94]
hi, im trying to delete all existing timers using the input of the node.

i already tried:

msg.payload = { timers: null, settings: null }
msg.payload = { timers: [], settings: {} }

and so on.

it looks like the undefined / null values are ignored.
is there any possibilty to delete the timers?

**Comment by fellinga** [comment]
Hi @simon276,

the nodes input expects a JSON **string**, not an object. You need to pass the payload like this:

`msg.payload = '{"timers":[],"settings":{}}';`

Please let me know if this helps!
