### ISSUE TITLE
Deploy in Node Red delete all timers

### ISSUE THREAD

**Issue by ThomasFTL** [fellinga/node-red-contrib-ui-time-scheduler#95]
When I change the flow and deploy, all timers are deleted.
This is a very poor basis for making changes to the flow.

I take the write file and read file nodes because there is no automation.

**Comment by fellinga** [comment]
Hi @ThomasFTL  please have a look at https://github.com/fellinga/node-red-contrib-ui-time-scheduler#restoring-schedules-after-a-reboot this section does not only refer to a reboot but also to a redeploy.

Please let me know if it helps!
